### ISSUE TITLE
Problems both compiling and running  on Linux

### ISSUE THREAD

**Issue by axb21** [melvic-ybanez/lohika#34]
I am interested in playing with lohika, but I ran into trouble running any of the releases or even compiling the code on Linux. and thought I would share my experience in case it helps the project and/or its documentation. The only combination that I managed to get working is compiling from source code using Java 20 (assembling and running the jar produced seems to work fine). The latest release does not run for me in any version of Java I tried (16, 17, 20, 21), and does not compile _except_ in Java 20.

I didn't see build instructions spelled out, but here's what I tried:

1. Clonining the project
2. `cd`ing into the `lohika` directory
3. Running `sbt`
4. Issuing `project ui`
5. Issuing `compile` or `assembly`

Here is the Java 21 error from `compile`:
```
sbt:lohika> project ui
[info] set current project to ui (in build file:/tmp/lohika/)
sbt:ui> compile
[info] compiling 26 Scala sources to /tmp/lohika/core/target/scala-3.5.0/classes ...
[error] -- [E008] Not Found Error: /tmp/lohika/core/src/main/scala/com/melvic/lohika/prover/programs/ProverProgram.scala:12:30 
[error] 12 |import java.text.NumberFormat.Style
[error]    |                              ^^^^^
[error]    |            value Style is not a member of object java.text.NumberFormat
[warn] there was 1 feature warning; re-run with -feature for details
[warn] one warning found
[error] one error found
[error] (core / Compile / compileIncremental) Compilation failed
[error] Total time: 6 s, completed Oct 29, 2024, 9:18:03 AM
sbt:ui> 
```

The code compiles and runs correctly with Java 20. It does not compile in Java 16 or Java 17 but I'll spare you the stack trace spam.

I am not able to run the JAR from the latest release (at time of writing, 0.3.0 I believe) on the Releases page in any of the versions of Java I tried. The errors given vary by Java version. Using Java 20 this is the error I see:

```
Oct 29, 2024 9:28:10 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @1a814726'
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:253)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:263)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:290)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:651)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:671)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        ... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:275)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:290)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:651)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:671)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:1623)
```

Using Java 21, this is what I see (a different-looking error):
```
Oct 29, 2024 9:29:50 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @5b8bc155'
GLFactory.static - Platform: Linux - not available: com.sun.prism.es2.X11GLFactory
java.lang.ClassNotFoundException: com.sun.prism.es2.X11GLFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:421)
        at java.base/java.lang.Class.forName(Class.java:412)
        at com.sun.prism.es2.GLFactory$FactoryLoader.run(GLFactory.java:101)
        at com.sun.prism.es2.GLFactory$FactoryLoader.run(GLFactory.java:91)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
        at com.sun.prism.es2.GLFactory.<clinit>(GLFactory.java:87)
        at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:71)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:421)
        at java.base/java.lang.Class.forName(Class.java:412)
        at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.ClassNotFoundException: com.sun.glass.ui.gtk.GtkPlatformFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:421)
        at java.base/java.lang.Class.forName(Class.java:412)
        at com.sun.glass.ui.PlatformFactory.getPlatformFactory(PlatformFactory.java:42)
        at com.sun.glass.ui.Application.run(Application.java:146)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:290)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:292)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:651)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:671)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Failed to load Glass factory class
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.sun.glass.ui.PlatformFactory.createApplication()" because the return value of "com.sun.glass.ui.PlatformFactory.getPlatformFactory()" is null
        at com.sun.glass.ui.Application.run(Application.java:146)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:290)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:292)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:651)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:671)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

I've tried Java 16 and 17 as well and the latest release jar will not run in either of those (I won't spam you with the stack traces). I did not try any previous versions, only the latest.

**Comment by melvic-ybanez** [comment]
Created a ticket for the Build instructions: https://github.com/melvic-ybanez/lohika/issues/40
